[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"

primaryColor = "#1677E8"
backgroundColor = "#F5F8FC"
secondaryBackgroundColor = "#EDF4FC"
textColor = "#1F2A3D"

font = "sans serif"